version: "3.7"
services:
  grav-page:
    build:
      context: ./grav-page
      args:
        GRAV_VERSION: 1.6.16
        GRAV_SHA1: 4FBB140FCF110C692A9D8102041C3F26B2FCA9DA
    image: devops-guide-grav:1.6.16
    ports:
      - "8080:80"
    volumes:
      - ./grav-page/user:/var/www/html/user
